### ISSUE TITLE
Cannot create HTML5 or Normalized DITA using test files on Windows

### ISSUE THREAD

**Issue by lief-erickson** [jason-fox/fox.jason.passthrough#1] opened 2019-09-16 22:38 UTC
Preprocess files on Windows are not recognized as passthrough

With the changes made in [bd3a551](https://github.com/jason-fox/fox.jason.passthrough/commit/bd3a5510b14681189c621125f83a018b60ecf320) I can create a PDF from `fox.jason.passthrough.pandoc\test\single-topic\document.ditamap`. I have tested various files from the `test` directory. I have also tested a simple rST file I have. With all of them I can produce a PDF.

But with none of them can I produce HTML or Normalized DITA.

The suspicion is that `preprocess` may be implicated because `preprocess2` is used for PDF. 

> Quick fix - amend the Normalize DITA plugin to use preprocess2 for now by changing the depends in org.dita.normalize/build.xml line 10.

This suggestion did not work for me. 

> I'll need the temp job.xml and the intermediate ditamap to look at.

Here you go. Attached is a the [temp directory](https://github.com/jason-fox/fox.jason.passthrough/files/3618404/temp.zip) from `\single-topic\document.ditamap` that may be helpful in debugging the issue.

Also, I notice this directory is sometimes created: `test\single-topic\${_dita.map.output.dir}`. Yes, that's the actual name of the directory.

Environment:
* Windows 10
* DITA-OT 3.3.3 (standalone)
* Oxygen 21.1 (using DITA-OT 3.3.3)

**Comment by jason-fox** [comment] 2019-09-17 18:58
The issue is once again Windows file path processing vs XML paths.

### Linux/Mac

#### Debug log - [read-job.xml] 

```
[read-job.xml] Applying com.oopsconsultancy.xmltask.AnonymousCallAction@77fec3b6 to 
//file[@result='file:/Users/jasonfox/Workspace/dita/dita-ot-3.3.3/plugins/
fox.jason.passthrough.pandoc/test/html-local-file/topic.dita']
```

#### .job.xml

```xml
<file src="file:/Users/jasonfox/Workspace/dita/dita-ot-3.3.3/plugins/
fox.jason.passthrough.pandoc/test/single-topic/markdown.md" 
 uri="markdown.md" path="markdown.md" 
result="file:/Users/jasonfox/Workspace/dita/dita-ot-3.3.3/plugins/
fox.jason.passthrough.pandoc/test/single-topic/markdown.md'" format="dita" target="true">
```

#### Windows

#### Debug log - [read-job.xml] 

```
[read-job.xml] Applying com.oopsconsultancy.xmltask.AnonymousCallAction@77fec3b6 to 
//file[@result='file:G:\git\dita-ot-3.3.3\plugins\
fox.jason.passthrough.pandoc\test\single-topic\markdown.md']
```
or even:

```
[read-job.xml] Applying com.oopsconsultancy.xmltask.AnonymousCallAction@77fec3b6 to 
//file[@result='file:C:\Program%20Files\Oxygen%20XML%20Editor%2021\frameworks\dita\DITA-OT3.x\plugins\
fox.jason.passthrough.pandoc\test\single-topic\markdown.md']
```

#### .job.xml

```xml
<file src="file:/G:/git/dita-ot-3.3.3/plugins
/fox.jason.passthrough.pandoc/test/single-topic/markdown.md"
 uri="markdown.md" path="markdown.md" 
result="file:/G:/git/dita-ot-3.3.3/plugins/
fox.jason.passthrough.pandoc/test/single-topic/markdown.md"  
format="dita" target="true">
```

Antlib line 100

```xml
<property name="result" value="file:${ditamap.dir}${file.separator}@{href}"/>
```

Will have to be replaced by a `<scriptdef>` function

**Comment by jason-fox** [comment] 2019-09-18 20:20
- Potential fix: d52829e
- Additional debug: ba6a881 - this should give more info in the log if `-v` is used.


@lief-erickson : As I'm fixing Windows blind, could you re-install the necessary plugins on your Windows system and try running again and provide more feedback as necessary. Thanks.

```console
dita --uninstall fox.jason.passthrough
dita --install https://github.com/jason-fox/fox.jason.passthrough/archive/master.zip
```

Another test could be to place the  `*.ditamap` under `C:\Program Files\` or indeed any directory with a space in it.

**Comment by lief-erickson** [comment] 2019-09-24 20:25
The potential fix was able to produce valid output using the sample test files from the plugin, but not without some lingering side effects.  When trying a more complex rST file I was running into some issues, but I'm not certain that they are the fault of the the passthrough plugin or belong to the preprocessing stage. 

I'll gather everything and update this ticket when I have it.

**Comment by jason-fox** [comment] 2019-10-03 18:53
@lief-erickson any further progress to report?

**Comment by lief-erickson** [comment] 2019-10-03 18:57
Yes. I'll post it later tonight (my time).

**Comment by lief-erickson** [comment] 2019-10-04 03:23
I'm going to record a couple of issues that I'm seeing here, but upon reflection not all of them may be with the passthrough or pandoc plugin and instead may be located elsewhere in the processor (although where exactly I'm not certain).

Issues:

- Using the `dita` output format does not produce files with `.dita` or `.xml` extension. Instead it is the source files extension even though the contents of the converted file are in fact DITA. I'm forced to rename the extension.
- Lists inside the `csv_table` (in the second column) are not rendered as an unordered list.
- Notes are not rendered as `<note>`.


This .zip file contains a sample rST file following similar structure as your other test files. Also included are the log file and temp directory as well as the output directory. In the output directory rename the .`.rst` file to `.dita` to see the transformed DITA.


This isn't a comprehensive test of what's possible in rST, but it's a start. Also, I'm a neophyte with rST, so there may be rST syntax errors that cause downstream issues. You may use and extend this sample as you wish.
[rst-sample1.zip](https://github.com/jason-fox/fox.jason.passthrough/files/3688822/rst-sample1.zip)

**Comment by jason-fox** [comment] 2019-10-04 07:03
None of the remaining issues touch the passthrough plug-in processing, they are all `pandoc` or `dita` transform related. I'll close this Windows processing issue, and raise three separate new issues in the pandoc plug-in.

**Closed as completed by jason-fox** 2019-10-04 07:03 UTC
Labels: bug
